### ISSUE TITLE
GIAB truth files (question)

### ISSUE THREAD

**Issue by andreas-wilm** [hall-lab/protocols#1]
Hey Colby,

is snp.indel.giab.validation.sh the script you used for validation in the speedseq paper? And, would it be possible for you to share the supposedly preproccessed giab 2.17 truth files with the public?

Many thanks,
Andreas

**Comment by cc2qe** [comment]
yeah, that's the script. I'd be happy to share the truth set, but the files are pretty large so I don't think I can do so permanently. But I'll upload the giab 2.17 truth for now

**Comment by cc2qe** [comment]
Ok those files are located here, and I'll make the available for at least a week: http://colbychiang.com/hall/speedseq/truth/giab.2.17

Also, our methods followed the strategy of the 2014 GIAB paper, but since publication I believe better methods for variant comparison have been released. I've never used it personally, but VT might be worth a shot: http://genome.sph.umich.edu/wiki/Vt

**Comment by andreas-wilm** [comment]
Excellent! All downloaded. Thanks a lot!
